name: Move assigned issue
on:
  issues:
    types:
      - assigned
jobs:
  move-assigned-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to in progress
        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        with:
          gh_token: ${{ secrets.TAIL_TRACKR_TOKEN }}
          organization: utmgdsc
          project_id: 9
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: In Progress
